### ISSUE TITLE
Can't read UTF BOM

### ISSUE THREAD

**Issue by lxith** [nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode#50]
The extension has trouble reading .ppm files encoded with byte order mark.

**Comment by BenWeisz** [comment]
Hi there, what is the endianness of your system?

**Comment by BenWeisz** [comment]
If you can, please also attach the file you were having trouble viewing with the extension. Thank you!

**Comment by lxith** [comment]
Sorry for the late reply, it is little endian.
(git doesn't support ppm attachments so I have changed the extension to .txt)
[output.txt](https://github.com/user-attachments/files/17371046/output.txt)

**Comment by Fryguy** [comment]
Looks like you have the UTF-16-LE BOM in your file: `FF FE`

**Comment by nagata-yoshiteru** [comment]
Hi @lxith, I tried to open your file using GIMP and IrfanView, but could not open it in either. I think the file is corrupt or does not conform to PPM specifications. ( I'm not sure if PPM supports UTF BOM. )

**Comment by BenWeisz** [comment]
@Fryguy @nagata-yoshiteru  Yes it looks like it has a UTF-16 BOM and all of the text data is encoded with that encoding.

@lxith The official standard specifies that the file encoding for ppm must be ASCII

> All characters referred to herein are encoded in ASCII.

Please see the official documentation: [NetPBM](https://netpbm.sourceforge.net/doc/ppm.html)

I suspect that you're either:
1) Redirecting console output on windows to a file
2) Using a bad file writer setup in C++, Rust or whichever language is generating this file

**Comment by laith-w** [comment]
Ah I see, I didn't know the standard did not support UTF BOM.

You're correct, I was redirecting output on Windows using Powershell. Command prompt outputs UTF-8 without BOM on my system however and works fine. The file is also read correctly by the extension if I convert the file encoding first.

I thought this was a bug since some other viewers would read my files fine (e.g. Rhodes College's web viewer : https://www.cs.rhodes.edu/welshc/COMP141_F16/ppmReader.html), but good to know now that PPM doesn't officially support BOM.

Thanks all, sorry for the trouble.

**Comment by lxith** [comment]
Ah I see, I didn't know the standard did not support UTF BOM.

You're correct, I was redirecting output on Windows using Powershell. Command prompt outputs UTF-8 without BOM on my system however and works fine. The file is also read correctly by the extension if I convert the file encoding first.

I thought this was a bug since some other viewers would read my files fine (e.g. Rhodes College's web viewer : https://www.cs.rhodes.edu/welshc/COMP141_F16/ppmReader.html), but good to know now that PPM doesn't officially support BOM.

Thanks all, sorry for the trouble.
